### ISSUE TITLE
Crash on split view

### ISSUE THREAD

**Issue by shuvashish76** [woheller69/eggtimer#12]
**Describe the bug**
App crashes when open it with split view

**To Reproduce**
1. Open the app
2. Long press recent button from device navigation bar for split view
 See error

**Crash logs**
```
FATAL EXCEPTION: main
Process: org.woheller69.eggtimer, PID: 11273
java.lang.RuntimeException: Unable to destroy activity {org.woheller69.eggtimer/org.woheller69.eggtimer.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4386)
	at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:4404)
	at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4678)
	at android.app.ActivityThread.-wrap18(Unknown Source:0)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1598)
	at android.os.Handler.dispatchMessage(Handler.java:106)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6518)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.os.CountDownTimer.cancel()' on a null object reference
	at org.woheller69.eggtimer.MainActivity.onDestroy(MainActivity.java:87)
	at android.app.Activity.performDestroy(Activity.java:7232)
	at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1250)
	at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:4373)
	... 10 more
```
**Device info:**
 - Device: Lenovo Tab4 8 plus
 - Andorid Version: 8.1.0
 - App Version: 1.6 (16)

**Comment by woheller69** [comment]
obviously your action performs onDestroy, so the app would not run anyway. In addition there is this NullPointerException which I can fix, but that will probably not solve the problem with split view
I never tried split view...

**Comment by shuvashish76** [comment]
Same type crash if you perform "_Freeform Multiwindow_" feature.

**Comment by woheller69** [comment]
should be fixed in next release
